name: Checking workflow

on: [push, workflow_dispatch]

jobs:
  test-go-version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.22'
          check-latest: true

      - name: Check go version
        run: go version

      - name: Run main file
        run: go run main.go
    
  test-go-version-file:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Go using .go-version file
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: Check go version
        run: go version 
      
      - name: Run main file
        run: go run main.go