name: Test workflow

on: [push, workflow_dispatch]

jobs:  
  test-v7:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7

      - run: |
          go version
    
  test-v6:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v6

      - run: |
          go version

  test-v5:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v5

      - run: |
          go version