name: Test caching behavior
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.21', '1.22', '1.10', '1.9']
    steps:
      - uses: actions/checkout@v7
      - uses: mahabaleshwars/setup-go@fix/756-cache
        with:
          go-version: ${{ matrix.go }}
      