name: Test workflow

on: [push, workflow_dispatch]

jobs:  
  test-v7:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: 1.23
          check-latest: true

      - name: Check go version
        run: go version
      
      - name: Run main
        run: go run main.go