name: Test workflow

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26

      - name: Run Go
        run: go mod tidy
        run: go test ./...