name: Test workflow

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v7
      - name: Set up Go
        uses: johnmaguire/setup-go@go-version-file-behavior
        with:
          go-version-file: go.mod
          go-version-file-behavior: 'latest-patch'
          check-latest: true

      - name: Check go version
        run: go version
      
      - name: Run main
        run: |
          go mod tidy
          go run main.go